#!flask/bin/python
#encoding=UTF-8
from app import db, models

db.session.add(models.segments(id = 'IT', bg_name = 'ИТ'))
db.session.add(models.segments(id = 'Tourism', bg_name = 'Туризъм'))
db.session.add(models.segments(id = 'Retail', bg_name = 'Продажби на дребно'))
db.session.add(models.segments(id = 'Insurance', bg_name = 'Застраховане'))
db.session.add(models.segments(id = 'Pharma', bg_name = 'Фармацевтичен сектор'))

db.session.add(models.segments_info(segment_id = 'IT', year_id = 1, segment_info = 'Устойчив разтеж. '))
db.session.add(models.segments_info(segment_id = 'Tourism', year_id = 1, segment_info = 'Секторът се радва предимно на по-нисък клас туристи.Българските туристи предпочитат пакети в България, Гърция и Турция.'))
db.session.add(models.segments_info(segment_id = 'Retail', year_id = 1, segment_info = 'Секторът е пренаситен. Конкуренцията води до занижена ценова политика.'))
db.session.add(models.segments_info(segment_id = 'Insurance', year_id = 1, segment_info = 'Доверието в сектора е изключително ниско.'))
db.session.add(models.segments_info(segment_id = 'Pharma', year_id = 1, segment_info = 'Секторът отчита печалба. '))
db.session.add(models.segments_info(segment_id = 'IT', year_id = 2, segment_info = 'Ръстът на икономиката на ЕС води до още по-голямо повишаване на разтежа.'))
db.session.add(models.segments_info(segment_id = 'Tourism', year_id = 2, segment_info = 'Започва мащабна кампания за привличане на по-висок клас туристи. '))
db.session.add(models.segments_info(segment_id = 'Retail', year_id = 2, segment_info = 'Последиците от финансовата криза все още налагат потребление на нисък клас стоки.'))
db.session.add(models.segments_info(segment_id = 'Insurance', year_id = 2, segment_info = 'Секторът е депресиран поради икономическата обстановка, но има стабилна, сигурна част от приходите поради определени задължителни застраховки.'))
db.session.add(models.segments_info(segment_id = 'Pharma', year_id = 2, segment_info = 'Сключва се нов рамков договор от големите производители с НЗОК за покриване на лекарства на осигурените лица.'))
db.session.add(models.segments_info(segment_id = 'IT', year_id = 3, segment_info = 'Привлечени са нови инвестиции от ЕС и САЩ за сектора.'))
db.session.add(models.segments_info(segment_id = 'Tourism', year_id = 3, segment_info = 'Годината се оказва с неблагоприятен климат по време на летния сезон в България. Същевременно българите покачват интереса си към по-далечни дестинации.'))
db.session.add(models.segments_info(segment_id = 'Retail', year_id = 3, segment_info = 'Нова държавна политика налага на големи рестрикции за синхрозирането на ценовата политика на големите вериги. '))
db.session.add(models.segments_info(segment_id = 'Insurance', year_id = 3, segment_info = 'Нова държавна политика в областта налага повече като обем и брой задължителни имуществени застраховки за бизнеса.'))
db.session.add(models.segments_info(segment_id = 'Pharma', year_id = 3, segment_info = 'НЗОК не може да посрещне задълженията си към сектора. Засилва се потреблението на хомеопатична и алтернативна медицина.'))
db.session.add(models.segments_info(segment_id = 'IT', year_id = 4, segment_info = 'Разтежът продължава, но се усеща липса на достатъчен брой кадри.'))
db.session.add(models.segments_info(segment_id = 'Tourism', year_id = 4, segment_info = 'Привличат се нови инвестиции за културния туризъм в страната.'))
db.session.add(models.segments_info(segment_id = 'Retail', year_id = 4, segment_info = 'Усеща се повишен импорт на европейски стоки, резултат от вътрешния пазар на ЕС'))
db.session.add(models.segments_info(segment_id = 'Insurance', year_id = 4, segment_info = 'Доверието в сектора се усилва. Повишава се леко и броя на личните застраховки.'))
db.session.add(models.segments_info(segment_id = 'Pharma', year_id = 4, segment_info = 'Потреблението на лекарства отчита спад поради засилена дължавна политика за насърчаване на профилактиката на здравето.'))
db.session.add(models.segments_info(segment_id = 'IT', year_id = 5, segment_info = 'В САЩ откриват нови технологични решения.Алтернативни аутсорсинг дестинации се оказват по-подготвени за навлизащите нови технологии.'))
db.session.add(models.segments_info(segment_id = 'Tourism', year_id = 5, segment_info = 'Изравнява се процентното съотношение между висок и нисък клас туристи. '))
db.session.add(models.segments_info(segment_id = 'Retail', year_id = 5, segment_info = 'Секторът отбелязва ръст в потреблението на по-висок клас стоки и отбелязва ръст в приходите си'))
db.session.add(models.segments_info(segment_id = 'Insurance', year_id = 5, segment_info = 'Поради природни катаклизми се налага изплащането на множество застрахователни премии. Секторът успява да понесе това финансово и се повишава доверието в него в края на календарната година.'))
db.session.add(models.segments_info(segment_id = 'Pharma', year_id = 5, segment_info = 'Нов регламент на ЕС подобрява състоянието на сектора чрез въвеждане на по-лесна и ефективна процедура за тестване на лекарствените продукти преди пускането им на европейския вътрешен пазар.'))

db.session.add(models.company_details(stock_id = 'NAS', company_name = '"Ню артсофт" ', segment_id = 'IT', market = 'Международен пазар', activity = 'Разработчик на приложения за мобилни устройства.'))
db.session.add(models.company_details(stock_id = 'PPL', company_name = '"Пипилс"', segment_id = 'IT', market = 'Международен пазар', activity = 'Разработчик на социални мрежи, пригодени да свързват гражданите на ЕС. '))
db.session.add(models.company_details(stock_id = 'CCS', company_name = '"Кобра компютърс" ', segment_id = 'IT', market = 'Международен пазар', activity = 'Разнообразни софтуерни решения, дистрибуция на хардуер.'))
db.session.add(models.company_details(stock_id = 'HRA', company_name = '"Хорека асистанс"', segment_id = 'IT', market = 'Международен пазар', activity = 'Специализиран софтуер за ресторанти и магазини'))
db.session.add(models.company_details(stock_id = 'PLG', company_name = '"Палас гардънс"', segment_id = 'Tourism', market = 'България', activity = 'Хотелска верига с 12 луксозни хотела в страната.'))
db.session.add(models.company_details(stock_id = 'RUT', company_name = '"Рустурс"', segment_id = 'Tourism', market = 'България и Русия', activity = 'Туроператор с множество клонове в Русия. Предлага пакетни услуги.'))
db.session.add(models.company_details(stock_id = 'VLG', company_name = '"Вилиджърс"', segment_id = 'Tourism', market = 'България', activity = 'Хотелиерски услуги за отдаване на  обекти в планински селски комплекси.'))
db.session.add(models.company_details(stock_id = 'CLS', company_name = '"Култшайн"', segment_id = 'Tourism', market = 'България', activity = 'Туристическа агенция номер 1 на пазара за екзотични почивки.'))
db.session.add(models.company_details(stock_id = 'BIN', company_name = '"Бионетс"', segment_id = 'Retail', market = 'Балкански полуостров', activity = 'Верига хипермаркети за биопродукти'))
db.session.add(models.company_details(stock_id = 'GRM', company_name = '"Гросмаркт"', segment_id = 'Retail', market = 'България', activity = 'Верига хипермаркети за стоки от среден клас'))
db.session.add(models.company_details(stock_id = 'MSP', company_name = '"Майшоп"', segment_id = 'Retail', market = 'ЕС', activity = 'Международна верига хипермаркети за стоки от висок клас, оперираща чрез клон в България'))
db.session.add(models.company_details(stock_id = 'TBB', company_name = '"Топбай БГ"', segment_id = 'Retail', market = 'България', activity = 'Верига хипермаркети за стоки от нисък клас'))
db.session.add(models.company_details(stock_id = 'SCT', company_name = '"Секюртайм"', segment_id = 'Insurance', market = 'България', activity = 'Застрахователно дружество предлагащо имуществено застраховане.'))
db.session.add(models.company_details(stock_id = 'CLR', company_name = '"Контрол рискинг"', segment_id = 'Insurance', market = 'България', activity = 'Застрахователно дружество предлагащо лично застраховане.'))
db.session.add(models.company_details(stock_id = 'STD', company_name = '"Си Ти Ди - груп"', segment_id = 'Insurance', market = 'България', activity = 'Застрахователно дружество, предглащо предимно автомобилно застраховане'))
db.session.add(models.company_details(stock_id = 'INB', company_name = '"Инсуранс БГ"', segment_id = 'Insurance', market = 'България', activity = 'Застрахователно дружество, насочено към задължителни професионални застраховки.'))
db.session.add(models.company_details(stock_id = 'BIP', company_name = '"Биопродуктс"', segment_id = 'Pharma', market = 'България', activity = 'Български производител на хомеопатични и био лекарствени продукти. '))
db.session.add(models.company_details(stock_id = 'FMP', company_name = '"Фарма Плюс"', segment_id = 'Pharma', market = 'България', activity = 'Български производител със силна диструбуционна мрежа, но слаб производствен капацитет.'))
db.session.add(models.company_details(stock_id = 'BFM', company_name = '"Булгафарма"', segment_id = 'Pharma', market = 'България', activity = 'Български производител на лекарствени продукти със силни връзки в сектора и добра дистрибуционна мрежа.'))
db.session.add(models.company_details(stock_id = 'FFM', company_name = '"Франсфарма"', segment_id = 'Pharma', market = 'България', activity = 'Български вносител на висококачествени лекарствени продукти от Франция. '))

db.session.add(models.stock_price(stock_id = 'NAS', time = 1, price = 10.32))
db.session.add(models.stock_price(stock_id = 'NAS', time = 2, price = 11.21))
db.session.add(models.stock_price(stock_id = 'NAS', time = 3, price = 11.66))
db.session.add(models.stock_price(stock_id = 'NAS', time = 4, price = 12.53))
db.session.add(models.stock_price(stock_id = 'NAS', time = 5, price = 13.59))
db.session.add(models.stock_price(stock_id = 'NAS', time = 6, price = 14.01))
db.session.add(models.stock_price(stock_id = 'NAS', time = 7, price = 14.59))
db.session.add(models.stock_price(stock_id = 'NAS', time = 8, price = 15.35))
db.session.add(models.stock_price(stock_id = 'NAS', time = 9, price = 15.54))
db.session.add(models.stock_price(stock_id = 'NAS', time = 10, price = 15.43))
db.session.add(models.stock_price(stock_id = 'NAS', time = 11, price = 16.11))
db.session.add(models.stock_price(stock_id = 'NAS', time = 12, price = 17.33))
db.session.add(models.stock_price(stock_id = 'NAS', time = 13, price = 15.32))
db.session.add(models.stock_price(stock_id = 'NAS', time = 14, price = 14.83))
db.session.add(models.stock_price(stock_id = 'NAS', time = 15, price = 13.22))
db.session.add(models.stock_price(stock_id = 'NAS', time = 16, price = 12.54))
db.session.add(models.stock_price(stock_id = 'NAS', time = 17, price = 8.32))
db.session.add(models.stock_price(stock_id = 'NAS', time = 18, price = 6.42))
db.session.add(models.stock_price(stock_id = 'NAS', time = 19, price = 4.1))
db.session.add(models.stock_price(stock_id = 'NAS', time = 20, price = 2))
db.session.add(models.stock_price(stock_id = 'PPL', time = 1, price = 4.4))
db.session.add(models.stock_price(stock_id = 'PPL', time = 2, price = 4.6))
db.session.add(models.stock_price(stock_id = 'PPL', time = 3, price = 4.8))
db.session.add(models.stock_price(stock_id = 'PPL', time = 4, price = 4.95))
db.session.add(models.stock_price(stock_id = 'PPL', time = 5, price = 5.1))
db.session.add(models.stock_price(stock_id = 'PPL', time = 6, price = 5.6))
db.session.add(models.stock_price(stock_id = 'PPL', time = 7, price = 7.13))
db.session.add(models.stock_price(stock_id = 'PPL', time = 8, price = 9.12))
db.session.add(models.stock_price(stock_id = 'PPL', time = 9, price = 13.32))
db.session.add(models.stock_price(stock_id = 'PPL', time = 10, price = 16.13))
db.session.add(models.stock_price(stock_id = 'PPL', time = 11, price = 19.12))
db.session.add(models.stock_price(stock_id = 'PPL', time = 12, price = 20.22))
db.session.add(models.stock_price(stock_id = 'PPL', time = 13, price = 21.21))
db.session.add(models.stock_price(stock_id = 'PPL', time = 14, price = 21.44))
db.session.add(models.stock_price(stock_id = 'PPL', time = 15, price = 22.12))
db.session.add(models.stock_price(stock_id = 'PPL', time = 16, price = 22.11))
db.session.add(models.stock_price(stock_id = 'PPL', time = 17, price = 21.1))
db.session.add(models.stock_price(stock_id = 'PPL', time = 18, price = 20.31))
db.session.add(models.stock_price(stock_id = 'PPL', time = 19, price = 19.22))
db.session.add(models.stock_price(stock_id = 'PPL', time = 20, price = 18.02))
db.session.add(models.stock_price(stock_id = 'CCS', time = 1, price = 5.1))
db.session.add(models.stock_price(stock_id = 'CCS', time = 2, price = 5.3))
db.session.add(models.stock_price(stock_id = 'CCS', time = 3, price = 5.4))
db.session.add(models.stock_price(stock_id = 'CCS', time = 4, price = 5.4))
db.session.add(models.stock_price(stock_id = 'CCS', time = 5, price = 5.5))
db.session.add(models.stock_price(stock_id = 'CCS', time = 6, price = 5.6))
db.session.add(models.stock_price(stock_id = 'CCS', time = 7, price = 5.9))
db.session.add(models.stock_price(stock_id = 'CCS', time = 8, price = 6.1))
db.session.add(models.stock_price(stock_id = 'CCS', time = 9, price = 6.1))
db.session.add(models.stock_price(stock_id = 'CCS', time = 10, price = 6))
db.session.add(models.stock_price(stock_id = 'CCS', time = 11, price = 5.9))
db.session.add(models.stock_price(stock_id = 'CCS', time = 12, price = 6))
db.session.add(models.stock_price(stock_id = 'CCS', time = 13, price = 6.1))
db.session.add(models.stock_price(stock_id = 'CCS', time = 14, price = 6.2))
db.session.add(models.stock_price(stock_id = 'CCS', time = 15, price = 6.1))
db.session.add(models.stock_price(stock_id = 'CCS', time = 16, price = 6.15))
db.session.add(models.stock_price(stock_id = 'CCS', time = 17, price = 6.25))
db.session.add(models.stock_price(stock_id = 'CCS', time = 18, price = 6.32))
db.session.add(models.stock_price(stock_id = 'CCS', time = 19, price = 6.35))
db.session.add(models.stock_price(stock_id = 'CCS', time = 20, price = 6.45))
db.session.add(models.stock_price(stock_id = 'HRA', time = 1, price = 6.1))
db.session.add(models.stock_price(stock_id = 'HRA', time = 2, price = 6))
db.session.add(models.stock_price(stock_id = 'HRA', time = 3, price = 6.12))
db.session.add(models.stock_price(stock_id = 'HRA', time = 4, price = 6.15))
db.session.add(models.stock_price(stock_id = 'HRA', time = 5, price = 6.11))
db.session.add(models.stock_price(stock_id = 'HRA', time = 6, price = 6.03))
db.session.add(models.stock_price(stock_id = 'HRA', time = 7, price = 5.95))
db.session.add(models.stock_price(stock_id = 'HRA', time = 8, price = 5.63))
db.session.add(models.stock_price(stock_id = 'HRA', time = 9, price = 5.44))
db.session.add(models.stock_price(stock_id = 'HRA', time = 10, price = 5.32))
db.session.add(models.stock_price(stock_id = 'HRA', time = 11, price = 5.2))
db.session.add(models.stock_price(stock_id = 'HRA', time = 12, price = 5.11))
db.session.add(models.stock_price(stock_id = 'HRA', time = 13, price = 5.21))
db.session.add(models.stock_price(stock_id = 'HRA', time = 14, price = 5.3))
db.session.add(models.stock_price(stock_id = 'HRA', time = 15, price = 5.38))
db.session.add(models.stock_price(stock_id = 'HRA', time = 16, price = 5.7))
db.session.add(models.stock_price(stock_id = 'HRA', time = 17, price = 5.82))
db.session.add(models.stock_price(stock_id = 'HRA', time = 18, price = 5.96))
db.session.add(models.stock_price(stock_id = 'HRA', time = 19, price = 6.12))
db.session.add(models.stock_price(stock_id = 'HRA', time = 20, price = 6.37))
db.session.add(models.stock_price(stock_id = 'PLG', time = 1, price = 8.1))
db.session.add(models.stock_price(stock_id = 'PLG', time = 2, price = 8.4))
db.session.add(models.stock_price(stock_id = 'PLG', time = 3, price = 8.23))
db.session.add(models.stock_price(stock_id = 'PLG', time = 4, price = 8.1))
db.session.add(models.stock_price(stock_id = 'PLG', time = 5, price = 8.2))
db.session.add(models.stock_price(stock_id = 'PLG', time = 6, price = 8.31))
db.session.add(models.stock_price(stock_id = 'PLG', time = 7, price = 8.4))
db.session.add(models.stock_price(stock_id = 'PLG', time = 8, price = 8.48))
db.session.add(models.stock_price(stock_id = 'PLG', time = 9, price = 8.45))
db.session.add(models.stock_price(stock_id = 'PLG', time = 10, price = 8.43))
db.session.add(models.stock_price(stock_id = 'PLG', time = 11, price = 8.39))
db.session.add(models.stock_price(stock_id = 'PLG', time = 12, price = 8.4))
db.session.add(models.stock_price(stock_id = 'PLG', time = 13, price = 8.38))
db.session.add(models.stock_price(stock_id = 'PLG', time = 14, price = 8.32))
db.session.add(models.stock_price(stock_id = 'PLG', time = 15, price = 8.24))
db.session.add(models.stock_price(stock_id = 'PLG', time = 16, price = 8.1))
db.session.add(models.stock_price(stock_id = 'PLG', time = 17, price = 8.08))
db.session.add(models.stock_price(stock_id = 'PLG', time = 18, price = 8.06))
db.session.add(models.stock_price(stock_id = 'PLG', time = 19, price = 7.98))
db.session.add(models.stock_price(stock_id = 'PLG', time = 20, price = 7.82))
db.session.add(models.stock_price(stock_id = 'RUT', time = 1, price = 7.1))
db.session.add(models.stock_price(stock_id = 'RUT', time = 2, price = 7.11))
db.session.add(models.stock_price(stock_id = 'RUT', time = 3, price = 7.18))
db.session.add(models.stock_price(stock_id = 'RUT', time = 4, price = 7.21))
db.session.add(models.stock_price(stock_id = 'RUT', time = 5, price = 7.1))
db.session.add(models.stock_price(stock_id = 'RUT', time = 6, price = 6.93))
db.session.add(models.stock_price(stock_id = 'RUT', time = 7, price = 6.83))
db.session.add(models.stock_price(stock_id = 'RUT', time = 8, price = 6.79))
db.session.add(models.stock_price(stock_id = 'RUT', time = 9, price = 6.51))
db.session.add(models.stock_price(stock_id = 'RUT', time = 10, price = 6.43))
db.session.add(models.stock_price(stock_id = 'RUT', time = 11, price = 6.21))
db.session.add(models.stock_price(stock_id = 'RUT', time = 12, price = 6.01))
db.session.add(models.stock_price(stock_id = 'RUT', time = 13, price = 5.93))
db.session.add(models.stock_price(stock_id = 'RUT', time = 14, price = 5.91))
db.session.add(models.stock_price(stock_id = 'RUT', time = 15, price = 5.82))
db.session.add(models.stock_price(stock_id = 'RUT', time = 16, price = 5.71))
db.session.add(models.stock_price(stock_id = 'RUT', time = 17, price = 5.74))
db.session.add(models.stock_price(stock_id = 'RUT', time = 18, price = 5.73))
db.session.add(models.stock_price(stock_id = 'RUT', time = 19, price = 5.77))
db.session.add(models.stock_price(stock_id = 'RUT', time = 20, price = 5.8))
db.session.add(models.stock_price(stock_id = 'VLG', time = 1, price = 4.5))
db.session.add(models.stock_price(stock_id = 'VLG', time = 2, price = 4.54))
db.session.add(models.stock_price(stock_id = 'VLG', time = 3, price = 4.58))
db.session.add(models.stock_price(stock_id = 'VLG', time = 4, price = 4.59))
db.session.add(models.stock_price(stock_id = 'VLG', time = 5, price = 4.62))
db.session.add(models.stock_price(stock_id = 'VLG', time = 6, price = 4.63))
db.session.add(models.stock_price(stock_id = 'VLG', time = 7, price = 4.66))
db.session.add(models.stock_price(stock_id = 'VLG', time = 8, price = 4.68))
db.session.add(models.stock_price(stock_id = 'VLG', time = 9, price = 4.74))
db.session.add(models.stock_price(stock_id = 'VLG', time = 10, price = 4.79))
db.session.add(models.stock_price(stock_id = 'VLG', time = 11, price = 4.81))
db.session.add(models.stock_price(stock_id = 'VLG', time = 12, price = 4.88))
db.session.add(models.stock_price(stock_id = 'VLG', time = 13, price = 4.93))
db.session.add(models.stock_price(stock_id = 'VLG', time = 14, price = 4.96))
db.session.add(models.stock_price(stock_id = 'VLG', time = 15, price = 5.01))
db.session.add(models.stock_price(stock_id = 'VLG', time = 16, price = 5.09))
db.session.add(models.stock_price(stock_id = 'VLG', time = 17, price = 5.11))
db.session.add(models.stock_price(stock_id = 'VLG', time = 18, price = 5.13))
db.session.add(models.stock_price(stock_id = 'VLG', time = 19, price = 5.15))
db.session.add(models.stock_price(stock_id = 'VLG', time = 20, price = 5.16))
db.session.add(models.stock_price(stock_id = 'CLS', time = 1, price = 8.34))
db.session.add(models.stock_price(stock_id = 'CLS', time = 2, price = 8.44))
db.session.add(models.stock_price(stock_id = 'CLS', time = 3, price = 8.46))
db.session.add(models.stock_price(stock_id = 'CLS', time = 4, price = 8.51))
db.session.add(models.stock_price(stock_id = 'CLS', time = 5, price = 8.6))
db.session.add(models.stock_price(stock_id = 'CLS', time = 6, price = 8.51))
db.session.add(models.stock_price(stock_id = 'CLS', time = 7, price = 8.64))
db.session.add(models.stock_price(stock_id = 'CLS', time = 8, price = 8.56))
db.session.add(models.stock_price(stock_id = 'CLS', time = 9, price = 8.52))
db.session.add(models.stock_price(stock_id = 'CLS', time = 10, price = 8.61))
db.session.add(models.stock_price(stock_id = 'CLS', time = 11, price = 8.69))
db.session.add(models.stock_price(stock_id = 'CLS', time = 12, price = 8.53))
db.session.add(models.stock_price(stock_id = 'CLS', time = 13, price = 8.64))
db.session.add(models.stock_price(stock_id = 'CLS', time = 14, price = 8.73))
db.session.add(models.stock_price(stock_id = 'CLS', time = 15, price = 8.79))
db.session.add(models.stock_price(stock_id = 'CLS', time = 16, price = 8.81))
db.session.add(models.stock_price(stock_id = 'CLS', time = 17, price = 8.83))
db.session.add(models.stock_price(stock_id = 'CLS', time = 18, price = 8.89))
db.session.add(models.stock_price(stock_id = 'CLS', time = 19, price = 8.93))
db.session.add(models.stock_price(stock_id = 'CLS', time = 20, price = 8.94))
db.session.add(models.stock_price(stock_id = 'BIN', time = 1, price = 9.24))
db.session.add(models.stock_price(stock_id = 'BIN', time = 2, price = 9.33))
db.session.add(models.stock_price(stock_id = 'BIN', time = 3, price = 9.37))
db.session.add(models.stock_price(stock_id = 'BIN', time = 4, price = 9.39))
db.session.add(models.stock_price(stock_id = 'BIN', time = 5, price = 9.42))
db.session.add(models.stock_price(stock_id = 'BIN', time = 6, price = 9.43))
db.session.add(models.stock_price(stock_id = 'BIN', time = 7, price = 9.44))
db.session.add(models.stock_price(stock_id = 'BIN', time = 8, price = 9.47))
db.session.add(models.stock_price(stock_id = 'BIN', time = 9, price = 9.51))
db.session.add(models.stock_price(stock_id = 'BIN', time = 10, price = 9.55))
db.session.add(models.stock_price(stock_id = 'BIN', time = 11, price = 9.59))
db.session.add(models.stock_price(stock_id = 'BIN', time = 12, price = 9.61))
db.session.add(models.stock_price(stock_id = 'BIN', time = 13, price = 9.68))
db.session.add(models.stock_price(stock_id = 'BIN', time = 14, price = 9.73))
db.session.add(models.stock_price(stock_id = 'BIN', time = 15, price = 9.75))
db.session.add(models.stock_price(stock_id = 'BIN', time = 16, price = 9.79))
db.session.add(models.stock_price(stock_id = 'BIN', time = 17, price = 9.81))
db.session.add(models.stock_price(stock_id = 'BIN', time = 18, price = 9.86))
db.session.add(models.stock_price(stock_id = 'BIN', time = 19, price = 9.91))
db.session.add(models.stock_price(stock_id = 'BIN', time = 20, price = 9.96))
db.session.add(models.stock_price(stock_id = 'GRM', time = 1, price = 8.18))
db.session.add(models.stock_price(stock_id = 'GRM', time = 2, price = 8.14))
db.session.add(models.stock_price(stock_id = 'GRM', time = 3, price = 8.1))
db.session.add(models.stock_price(stock_id = 'GRM', time = 4, price = 8.05))
db.session.add(models.stock_price(stock_id = 'GRM', time = 5, price = 8.07))
db.session.add(models.stock_price(stock_id = 'GRM', time = 6, price = 8.08))
db.session.add(models.stock_price(stock_id = 'GRM', time = 7, price = 8.1))
db.session.add(models.stock_price(stock_id = 'GRM', time = 8, price = 8.08))
db.session.add(models.stock_price(stock_id = 'GRM', time = 9, price = 8.11))
db.session.add(models.stock_price(stock_id = 'GRM', time = 10, price = 8.15))
db.session.add(models.stock_price(stock_id = 'GRM', time = 11, price = 8.18))
db.session.add(models.stock_price(stock_id = 'GRM', time = 12, price = 8.21))
db.session.add(models.stock_price(stock_id = 'GRM', time = 13, price = 8.2))
db.session.add(models.stock_price(stock_id = 'GRM', time = 14, price = 8.14))
db.session.add(models.stock_price(stock_id = 'GRM', time = 15, price = 8.22))
db.session.add(models.stock_price(stock_id = 'GRM', time = 16, price = 8.2))
db.session.add(models.stock_price(stock_id = 'GRM', time = 17, price = 8.25))
db.session.add(models.stock_price(stock_id = 'GRM', time = 18, price = 8.29))
db.session.add(models.stock_price(stock_id = 'GRM', time = 19, price = 8.31))
db.session.add(models.stock_price(stock_id = 'GRM', time = 20, price = 8.36))
db.session.add(models.stock_price(stock_id = 'MSP', time = 1, price = 18.21))
db.session.add(models.stock_price(stock_id = 'MSP', time = 2, price = 18.19))
db.session.add(models.stock_price(stock_id = 'MSP', time = 3, price = 18.17))
db.session.add(models.stock_price(stock_id = 'MSP', time = 4, price = 18.08))
db.session.add(models.stock_price(stock_id = 'MSP', time = 5, price = 17.92))
db.session.add(models.stock_price(stock_id = 'MSP', time = 6, price = 17.84))
db.session.add(models.stock_price(stock_id = 'MSP', time = 7, price = 17.72))
db.session.add(models.stock_price(stock_id = 'MSP', time = 8, price = 17.67))
db.session.add(models.stock_price(stock_id = 'MSP', time = 9, price = 17.68))
db.session.add(models.stock_price(stock_id = 'MSP', time = 10, price = 17.69))
db.session.add(models.stock_price(stock_id = 'MSP', time = 11, price = 17.72))
db.session.add(models.stock_price(stock_id = 'MSP', time = 12, price = 17.79))
db.session.add(models.stock_price(stock_id = 'MSP', time = 13, price = 17.82))
db.session.add(models.stock_price(stock_id = 'MSP', time = 14, price = 17.85))
db.session.add(models.stock_price(stock_id = 'MSP', time = 15, price = 17.88))
db.session.add(models.stock_price(stock_id = 'MSP', time = 16, price = 17.9))
db.session.add(models.stock_price(stock_id = 'MSP', time = 17, price = 18.01))
db.session.add(models.stock_price(stock_id = 'MSP', time = 18, price = 18.12))
db.session.add(models.stock_price(stock_id = 'MSP', time = 19, price = 18.18))
db.session.add(models.stock_price(stock_id = 'MSP', time = 20, price = 18.21))
db.session.add(models.stock_price(stock_id = 'TBB', time = 1, price = 14.54))
db.session.add(models.stock_price(stock_id = 'TBB', time = 2, price = 14.61))
db.session.add(models.stock_price(stock_id = 'TBB', time = 3, price = 14.69))
db.session.add(models.stock_price(stock_id = 'TBB', time = 4, price = 14.73))
db.session.add(models.stock_price(stock_id = 'TBB', time = 5, price = 14.77))
db.session.add(models.stock_price(stock_id = 'TBB', time = 6, price = 14.79))
db.session.add(models.stock_price(stock_id = 'TBB', time = 7, price = 14.78))
db.session.add(models.stock_price(stock_id = 'TBB', time = 8, price = 14.81))
db.session.add(models.stock_price(stock_id = 'TBB', time = 9, price = 14.62))
db.session.add(models.stock_price(stock_id = 'TBB', time = 10, price = 14.51))
db.session.add(models.stock_price(stock_id = 'TBB', time = 11, price = 14.31))
db.session.add(models.stock_price(stock_id = 'TBB', time = 12, price = 13.93))
db.session.add(models.stock_price(stock_id = 'TBB', time = 13, price = 13.96))
db.session.add(models.stock_price(stock_id = 'TBB', time = 14, price = 13.98))
db.session.add(models.stock_price(stock_id = 'TBB', time = 15, price = 14.01))
db.session.add(models.stock_price(stock_id = 'TBB', time = 16, price = 14.12))
db.session.add(models.stock_price(stock_id = 'TBB', time = 17, price = 14.19))
db.session.add(models.stock_price(stock_id = 'TBB', time = 18, price = 14.25))
db.session.add(models.stock_price(stock_id = 'TBB', time = 19, price = 14.29))
db.session.add(models.stock_price(stock_id = 'TBB', time = 20, price = 14.36))
db.session.add(models.stock_price(stock_id = 'SCT', time = 1, price = 15.15))
db.session.add(models.stock_price(stock_id = 'SCT', time = 2, price = 15.16))
db.session.add(models.stock_price(stock_id = 'SCT', time = 3, price = 15.17))
db.session.add(models.stock_price(stock_id = 'SCT', time = 4, price = 15.18))
db.session.add(models.stock_price(stock_id = 'SCT', time = 5, price = 15.19))
db.session.add(models.stock_price(stock_id = 'SCT', time = 6, price = 15.2))
db.session.add(models.stock_price(stock_id = 'SCT', time = 7, price = 15.21))
db.session.add(models.stock_price(stock_id = 'SCT', time = 8, price = 15.22))
db.session.add(models.stock_price(stock_id = 'SCT', time = 9, price = 15.23))
db.session.add(models.stock_price(stock_id = 'SCT', time = 10, price = 15.23))
db.session.add(models.stock_price(stock_id = 'SCT', time = 11, price = 15.23))
db.session.add(models.stock_price(stock_id = 'SCT', time = 12, price = 15.25))
db.session.add(models.stock_price(stock_id = 'SCT', time = 13, price = 15.26))
db.session.add(models.stock_price(stock_id = 'SCT', time = 14, price = 15.29))
db.session.add(models.stock_price(stock_id = 'SCT', time = 15, price = 15.31))
db.session.add(models.stock_price(stock_id = 'SCT', time = 16, price = 15.33))
db.session.add(models.stock_price(stock_id = 'SCT', time = 17, price = 15))
db.session.add(models.stock_price(stock_id = 'SCT', time = 18, price = 14.9))
db.session.add(models.stock_price(stock_id = 'SCT', time = 19, price = 15.22))
db.session.add(models.stock_price(stock_id = 'SCT', time = 20, price = 15.31))
db.session.add(models.stock_price(stock_id = 'CLR', time = 1, price = 9.1))
db.session.add(models.stock_price(stock_id = 'CLR', time = 2, price = 9.11))
db.session.add(models.stock_price(stock_id = 'CLR', time = 3, price = 9.1))
db.session.add(models.stock_price(stock_id = 'CLR', time = 4, price = 9.09))
db.session.add(models.stock_price(stock_id = 'CLR', time = 5, price = 9.1))
db.session.add(models.stock_price(stock_id = 'CLR', time = 6, price = 9.12))
db.session.add(models.stock_price(stock_id = 'CLR', time = 7, price = 9.13))
db.session.add(models.stock_price(stock_id = 'CLR', time = 8, price = 9.12))
db.session.add(models.stock_price(stock_id = 'CLR', time = 9, price = 9.13))
db.session.add(models.stock_price(stock_id = 'CLR', time = 10, price = 9.15))
db.session.add(models.stock_price(stock_id = 'CLR', time = 11, price = 9.17))
db.session.add(models.stock_price(stock_id = 'CLR', time = 12, price = 9.18))
db.session.add(models.stock_price(stock_id = 'CLR', time = 13, price = 9.2))
db.session.add(models.stock_price(stock_id = 'CLR', time = 14, price = 9.27))
db.session.add(models.stock_price(stock_id = 'CLR', time = 15, price = 9.31))
db.session.add(models.stock_price(stock_id = 'CLR', time = 16, price = 9.35))
db.session.add(models.stock_price(stock_id = 'CLR', time = 17, price = 9.38))
db.session.add(models.stock_price(stock_id = 'CLR', time = 18, price = 9.41))
db.session.add(models.stock_price(stock_id = 'CLR', time = 19, price = 9.45))
db.session.add(models.stock_price(stock_id = 'CLR', time = 20, price = 9.51))
db.session.add(models.stock_price(stock_id = 'STD', time = 1, price = 7.8))
db.session.add(models.stock_price(stock_id = 'STD', time = 2, price = 7.77))
db.session.add(models.stock_price(stock_id = 'STD', time = 3, price = 7.73))
db.session.add(models.stock_price(stock_id = 'STD', time = 4, price = 7.7))
db.session.add(models.stock_price(stock_id = 'STD', time = 5, price = 7.74))
db.session.add(models.stock_price(stock_id = 'STD', time = 6, price = 7.76))
db.session.add(models.stock_price(stock_id = 'STD', time = 7, price = 7.77))
db.session.add(models.stock_price(stock_id = 'STD', time = 8, price = 7.69))
db.session.add(models.stock_price(stock_id = 'STD', time = 9, price = 7.64))
db.session.add(models.stock_price(stock_id = 'STD', time = 10, price = 7.65))
db.session.add(models.stock_price(stock_id = 'STD', time = 11, price = 7.7))
db.session.add(models.stock_price(stock_id = 'STD', time = 12, price = 7.71))
db.session.add(models.stock_price(stock_id = 'STD', time = 13, price = 7.7))
db.session.add(models.stock_price(stock_id = 'STD', time = 14, price = 7.72))
db.session.add(models.stock_price(stock_id = 'STD', time = 15, price = 7.75))
db.session.add(models.stock_price(stock_id = 'STD', time = 16, price = 7.79))
db.session.add(models.stock_price(stock_id = 'STD', time = 17, price = 7.3))
db.session.add(models.stock_price(stock_id = 'STD', time = 18, price = 7.1))
db.session.add(models.stock_price(stock_id = 'STD', time = 19, price = 6.8))
db.session.add(models.stock_price(stock_id = 'STD', time = 20, price = 6.4))
db.session.add(models.stock_price(stock_id = 'INB', time = 1, price = 4.52))
db.session.add(models.stock_price(stock_id = 'INB', time = 2, price = 4.41))
db.session.add(models.stock_price(stock_id = 'INB', time = 3, price = 4.45))
db.session.add(models.stock_price(stock_id = 'INB', time = 4, price = 4.4))
db.session.add(models.stock_price(stock_id = 'INB', time = 5, price = 4.38))
db.session.add(models.stock_price(stock_id = 'INB', time = 6, price = 4.32))
db.session.add(models.stock_price(stock_id = 'INB', time = 7, price = 4.1))
db.session.add(models.stock_price(stock_id = 'INB', time = 8, price = 4.02))
db.session.add(models.stock_price(stock_id = 'INB', time = 9, price = 4.03))
db.session.add(models.stock_price(stock_id = 'INB', time = 10, price = 4.11))
db.session.add(models.stock_price(stock_id = 'INB', time = 11, price = 4.13))
db.session.add(models.stock_price(stock_id = 'INB', time = 12, price = 4.15))
db.session.add(models.stock_price(stock_id = 'INB', time = 13, price = 4.19))
db.session.add(models.stock_price(stock_id = 'INB', time = 14, price = 4.23))
db.session.add(models.stock_price(stock_id = 'INB', time = 15, price = 4.27))
db.session.add(models.stock_price(stock_id = 'INB', time = 16, price = 4.29))
db.session.add(models.stock_price(stock_id = 'INB', time = 17, price = 4.32))
db.session.add(models.stock_price(stock_id = 'INB', time = 18, price = 4.36))
db.session.add(models.stock_price(stock_id = 'INB', time = 19, price = 4.44))
db.session.add(models.stock_price(stock_id = 'INB', time = 20, price = 4.51))
db.session.add(models.stock_price(stock_id = 'BIP', time = 1, price = 1.2))
db.session.add(models.stock_price(stock_id = 'BIP', time = 2, price = 1.2))
db.session.add(models.stock_price(stock_id = 'BIP', time = 3, price = 1.19))
db.session.add(models.stock_price(stock_id = 'BIP', time = 4, price = 1.18))
db.session.add(models.stock_price(stock_id = 'BIP', time = 5, price = 1.21))
db.session.add(models.stock_price(stock_id = 'BIP', time = 6, price = 1.23))
db.session.add(models.stock_price(stock_id = 'BIP', time = 7, price = 1.24))
db.session.add(models.stock_price(stock_id = 'BIP', time = 8, price = 1.28))
db.session.add(models.stock_price(stock_id = 'BIP', time = 9, price = 1.31))
db.session.add(models.stock_price(stock_id = 'BIP', time = 10, price = 1.34))
db.session.add(models.stock_price(stock_id = 'BIP', time = 11, price = 1.4))
db.session.add(models.stock_price(stock_id = 'BIP', time = 12, price = 1.41))
db.session.add(models.stock_price(stock_id = 'BIP', time = 13, price = 1.4))
db.session.add(models.stock_price(stock_id = 'BIP', time = 14, price = 1.39))
db.session.add(models.stock_price(stock_id = 'BIP', time = 15, price = 1.35))
db.session.add(models.stock_price(stock_id = 'BIP', time = 16, price = 1.33))
db.session.add(models.stock_price(stock_id = 'BIP', time = 17, price = 1.29))
db.session.add(models.stock_price(stock_id = 'BIP', time = 18, price = 1.31))
db.session.add(models.stock_price(stock_id = 'BIP', time = 19, price = 1.31))
db.session.add(models.stock_price(stock_id = 'BIP', time = 20, price = 1.34))
db.session.add(models.stock_price(stock_id = 'FMP', time = 1, price = 5.55))
db.session.add(models.stock_price(stock_id = 'FMP', time = 2, price = 5.49))
db.session.add(models.stock_price(stock_id = 'FMP', time = 3, price = 5.4))
db.session.add(models.stock_price(stock_id = 'FMP', time = 4, price = 5.3))
db.session.add(models.stock_price(stock_id = 'FMP', time = 5, price = 5.34))
db.session.add(models.stock_price(stock_id = 'FMP', time = 6, price = 5.39))
db.session.add(models.stock_price(stock_id = 'FMP', time = 7, price = 5.41))
db.session.add(models.stock_price(stock_id = 'FMP', time = 8, price = 5.45))
db.session.add(models.stock_price(stock_id = 'FMP', time = 9, price = 5.55))
db.session.add(models.stock_price(stock_id = 'FMP', time = 10, price = 5.6))
db.session.add(models.stock_price(stock_id = 'FMP', time = 11, price = 5.61))
db.session.add(models.stock_price(stock_id = 'FMP', time = 12, price = 5.64))
db.session.add(models.stock_price(stock_id = 'FMP', time = 13, price = 5.68))
db.session.add(models.stock_price(stock_id = 'FMP', time = 14, price = 5.72))
db.session.add(models.stock_price(stock_id = 'FMP', time = 15, price = 5.74))
db.session.add(models.stock_price(stock_id = 'FMP', time = 16, price = 5.77))
db.session.add(models.stock_price(stock_id = 'FMP', time = 17, price = 5.79))
db.session.add(models.stock_price(stock_id = 'FMP', time = 18, price = 5.82))
db.session.add(models.stock_price(stock_id = 'FMP', time = 19, price = 5.85))
db.session.add(models.stock_price(stock_id = 'FMP', time = 20, price = 5.88))
db.session.add(models.stock_price(stock_id = 'BFM', time = 1, price = 10.9))
db.session.add(models.stock_price(stock_id = 'BFM', time = 2, price = 10.95))
db.session.add(models.stock_price(stock_id = 'BFM', time = 3, price = 10.98))
db.session.add(models.stock_price(stock_id = 'BFM', time = 4, price = 11.01))
db.session.add(models.stock_price(stock_id = 'BFM', time = 5, price = 11.32))
db.session.add(models.stock_price(stock_id = 'BFM', time = 6, price = 11.43))
db.session.add(models.stock_price(stock_id = 'BFM', time = 7, price = 11.56))
db.session.add(models.stock_price(stock_id = 'BFM', time = 8, price = 11.68))
db.session.add(models.stock_price(stock_id = 'BFM', time = 9, price = 11.61))
db.session.add(models.stock_price(stock_id = 'BFM', time = 10, price = 11.51))
db.session.add(models.stock_price(stock_id = 'BFM', time = 11, price = 11.38))
db.session.add(models.stock_price(stock_id = 'BFM', time = 12, price = 11.1))
db.session.add(models.stock_price(stock_id = 'BFM', time = 13, price = 11.15))
db.session.add(models.stock_price(stock_id = 'BFM', time = 14, price = 11.14))
db.session.add(models.stock_price(stock_id = 'BFM', time = 15, price = 11.18))
db.session.add(models.stock_price(stock_id = 'BFM', time = 16, price = 11.21))
db.session.add(models.stock_price(stock_id = 'BFM', time = 17, price = 11.11))
db.session.add(models.stock_price(stock_id = 'BFM', time = 18, price = 11.02))
db.session.add(models.stock_price(stock_id = 'BFM', time = 19, price = 10.92))
db.session.add(models.stock_price(stock_id = 'BFM', time = 20, price = 10.83))
db.session.add(models.stock_price(stock_id = 'FFM', time = 1, price = 6.34))
db.session.add(models.stock_price(stock_id = 'FFM', time = 2, price = 6.31))
db.session.add(models.stock_price(stock_id = 'FFM', time = 3, price = 6.3))
db.session.add(models.stock_price(stock_id = 'FFM', time = 4, price = 6.25))
db.session.add(models.stock_price(stock_id = 'FFM', time = 5, price = 6.26))
db.session.add(models.stock_price(stock_id = 'FFM', time = 6, price = 6.27))
db.session.add(models.stock_price(stock_id = 'FFM', time = 7, price = 6.2))
db.session.add(models.stock_price(stock_id = 'FFM', time = 8, price = 6.29))
db.session.add(models.stock_price(stock_id = 'FFM', time = 9, price = 6.31))
db.session.add(models.stock_price(stock_id = 'FFM', time = 10, price = 6.4))
db.session.add(models.stock_price(stock_id = 'FFM', time = 11, price = 6.38))
db.session.add(models.stock_price(stock_id = 'FFM', time = 12, price = 6.51))
db.session.add(models.stock_price(stock_id = 'FFM', time = 13, price = 6.42))
db.session.add(models.stock_price(stock_id = 'FFM', time = 14, price = 6.01))
db.session.add(models.stock_price(stock_id = 'FFM', time = 15, price = 5.33))
db.session.add(models.stock_price(stock_id = 'FFM', time = 16, price = 5.12))
db.session.add(models.stock_price(stock_id = 'FFM', time = 17, price = 2))
db.session.add(models.stock_price(stock_id = 'FFM', time = 18, price = 1))
db.session.add(models.stock_price(stock_id = 'FFM', time = 19, price = 0))
db.session.add(models.stock_price(stock_id = 'FFM', time = 20, price = 0))

db.session.add(models.stock_divident(stock_id = 'NAS', divident_period = 1, amount = 0, company_information = 'Разработват приложение насочено към оптимализация на транспортните услуги в столицата. '))
db.session.add(models.stock_divident(stock_id = 'PPL', divident_period = 1, amount = 0, company_information = 'Работят върху концепцията на нова социана мрежа.'))
db.session.add(models.stock_divident(stock_id = 'CCS', divident_period = 1, amount = 0, company_information = 'Покриват голям процент от територията на България с магазините си за хардуер.'))
db.session.add(models.stock_divident(stock_id = 'HRA', divident_period = 1, amount = 0, company_information = 'Имат множество договори с компании от средния бизнес.'))
db.session.add(models.stock_divident(stock_id = 'PLG', divident_period = 1, amount = 0, company_information = 'Не успяват да запълнят легловата си база за летния сезон. Обектите им в зимни курорти бележат отчитат печалба'))
db.session.add(models.stock_divident(stock_id = 'RUT', divident_period = 1, amount = 0, company_information = 'Имат стабилни позиции на Руския пазар и успяват да привлекат множество руски туристи през летния сезон в България'))
db.session.add(models.stock_divident(stock_id = 'VLG', divident_period = 1, amount = 0, company_information = 'Радват се на стабилна клиентска маса, но конкуренцията в бранша е голяма.'))
db.session.add(models.stock_divident(stock_id = 'CLS', divident_period = 1, amount = 0, company_information = 'Агенцията има стабилна репутация на пазара, но малък процент от българските туристи избират пакетните и услуги, поради високите цени на предлагане.'))
db.session.add(models.stock_divident(stock_id = 'BIN', divident_period = 1, amount = 0, company_information = 'Компанията има стабилна,но сравнително малка клиентска маса в големите градове в България. В процес на изготвяне на проект за изграждане на търговски обекти в Гърция.'))
db.session.add(models.stock_divident(stock_id = 'GRM', divident_period = 1, amount = 0, company_information = 'Силната диференциация в доходите на населението определеля по-малък пазарен дел.'))
db.session.add(models.stock_divident(stock_id = 'MSP', divident_period = 1, amount = 0, company_information = 'Резултатите от българския пазар са доста по-ниски от очакваното. Успява да компенсира от обектите си в други страни на ЕС.'))
db.session.add(models.stock_divident(stock_id = 'TBB', divident_period = 1, amount = 0, company_information = 'Компанията провежда агресивна ценова политика с цел да завладее по-висок пазарен дял на българския пазар.'))
db.session.add(models.stock_divident(stock_id = 'SCT', divident_period = 1, amount = 0, company_information = 'Финансово стабилно. '))
db.session.add(models.stock_divident(stock_id = 'CLR', divident_period = 1, amount = 0, company_information = 'Малък пазарен дял. '))
db.session.add(models.stock_divident(stock_id = 'STD', divident_period = 1, amount = 0, company_information = 'Среден пазарен дял. Печалбите са под прогнозираните резултати'))
db.session.add(models.stock_divident(stock_id = 'INB', divident_period = 1, amount = 0, company_information = 'Компанията е финансово нестабилна. '))
db.session.add(models.stock_divident(stock_id = 'BIP', divident_period = 1, amount = 0, company_information = 'Страда от слаба дистрибуционна мрежа.'))
db.session.add(models.stock_divident(stock_id = 'FMP', divident_period = 1, amount = 0, company_information = 'Не успява да изпълни всички получени заявки за доставка на лекарства в търговската мрежа.'))
db.session.add(models.stock_divident(stock_id = 'BFM', divident_period = 1, amount = 0, company_information = 'Прави мащабна рекламна кампания на продуктите си.'))
db.session.add(models.stock_divident(stock_id = 'FFM', divident_period = 1, amount = 0, company_information = 'Крайният потребител предпочита по-нискокласни лекарствени продукти.'))
db.session.add(models.stock_divident(stock_id = 'NAS', divident_period = 2, amount = 0.5, company_information = 'Капитализират на база добри връзки в сектора.'))
db.session.add(models.stock_divident(stock_id = 'PPL', divident_period = 2, amount = 0, company_information = 'Техническата част на проекта им е готова, но имат нужда от допълнителни инвестиции, за да го пуснат на пазара. '))
db.session.add(models.stock_divident(stock_id = 'CCS', divident_period = 2, amount = 0.3, company_information = 'Сключват екслузивен договор с немска компания за дистрибуция в Германия на хардуер.'))
db.session.add(models.stock_divident(stock_id = 'HRA', divident_period = 2, amount = 0.98, company_information = 'Появява се конкурент на пазара.'))
db.session.add(models.stock_divident(stock_id = 'PLG', divident_period = 2, amount = 0.1, company_information = 'Сключват договор с израелски туроператор за пакетна услуга от висок клас за летния сезон.'))
db.session.add(models.stock_divident(stock_id = 'RUT', divident_period = 2, amount = 0.3, company_information = 'Заведен е съдебен процес срещу тях от потребители, чийто пакетни услуги не са се осъществили поради фалит на компанията превозвач.'))
db.session.add(models.stock_divident(stock_id = 'VLG', divident_period = 2, amount = 0.23, company_information = 'Започват да работят по проект за развитие на екологичен туризъм и кандидатстват за субсидии от ЕС.'))
db.session.add(models.stock_divident(stock_id = 'CLS', divident_period = 2, amount = 0.3, company_information = 'С нова ценова политика разширяват клиентите си.'))
db.session.add(models.stock_divident(stock_id = 'BIN', divident_period = 2, amount = 0.4, company_information = 'Веригата започва изграждането на новите търговски обекти в Гърция. Нуждае се от нови инвестиции.'))
db.session.add(models.stock_divident(stock_id = 'GRM', divident_period = 2, amount = 0.3, company_information = 'Започват изграждане на малки 10 тъговски обекта на места с голям човекопоток.'))
db.session.add(models.stock_divident(stock_id = 'MSP', divident_period = 2, amount = 0.1, company_information = 'Не успява да се наложи на пазара поради високата си ценова политика. Отклонява се драстично от планираните резултати за предходната година.'))
db.session.add(models.stock_divident(stock_id = 'TBB', divident_period = 2, amount = 0.9, company_information = 'Ценовата политика дава резултат, пазарният им дял се увеличава, но печалбата е малка. '))
db.session.add(models.stock_divident(stock_id = 'SCT', divident_period = 2, amount = 0.8, company_information = 'Капитализира добре.'))
db.session.add(models.stock_divident(stock_id = 'CLR', divident_period = 2, amount = 0.4, company_information = 'Поради добро планиране е финансово стабилно'))
db.session.add(models.stock_divident(stock_id = 'STD', divident_period = 2, amount = 0.1, company_information = 'Започва агресивна ценова политика с най-ниски цени на предлаганите застрахователни продукти. '))
db.session.add(models.stock_divident(stock_id = 'INB', divident_period = 2, amount = 0.1, company_information = 'Изпитва затруднения да покрие застрахователните премии, които дължи.'))
db.session.add(models.stock_divident(stock_id = 'BIP', divident_period = 2, amount = 0.02, company_information = 'Привлича нови инвеститори от САЩ и успява да подобри връзките си с търговската мрежа.'))
db.session.add(models.stock_divident(stock_id = 'FMP', divident_period = 2, amount = 0.1, company_information = 'Започва изграждането на нов завод за лекарства и успява да привлече нови инвеститори.'))
db.session.add(models.stock_divident(stock_id = 'BFM', divident_period = 2, amount = 0.8, company_information = 'Успява да се наложи като производител номер 1 на пазара.'))
db.session.add(models.stock_divident(stock_id = 'FFM', divident_period = 2, amount = 0, company_information = 'Опитва се да задълбочи контактите си в търговската мрежа, инвестирайки цялата печалба за предходната година в това.'))
db.session.add(models.stock_divident(stock_id = 'NAS', divident_period = 3, amount = 0.7, company_information = 'Започват разработване на ново приложение за ресторанти.'))
db.session.add(models.stock_divident(stock_id = 'PPL', divident_period = 3, amount = 0, company_information = 'Поради добрата концепция на разработената нова социална мрежа, веднага след пускането и на пазара, тя се радва на успех'))
db.session.add(models.stock_divident(stock_id = 'CCS', divident_period = 3, amount = 0.35, company_information = 'Имат проблеми с поддръжката на дистрибутирания хардуер в Германия'))
db.session.add(models.stock_divident(stock_id = 'HRA', divident_period = 3, amount = 0.2, company_information = 'Губят трима от основните си клиенти.'))
db.session.add(models.stock_divident(stock_id = 'PLG', divident_period = 3, amount = 0.15, company_information = 'Започват стоеж на  13-ти хотелски комплекс на Черноморието.'))
db.session.add(models.stock_divident(stock_id = 'RUT', divident_period = 3, amount = 0.1, company_information = 'Туроператорът е финансово нестабилен поради обезщетенията, които следва да изплати на потребителите.'))
db.session.add(models.stock_divident(stock_id = 'VLG', divident_period = 3, amount = 0.2, company_information = 'Получават субсидия от ЕС, с която започват изграждане на еко пътеки около притежаваните от тях комплекси.'))
db.session.add(models.stock_divident(stock_id = 'CLS', divident_period = 3, amount = 0, company_information = 'Оборотът се покачва, но печалбата бележи спад.'))
db.session.add(models.stock_divident(stock_id = 'BIN', divident_period = 3, amount = 0.3, company_information = 'Получава банково кредитиране и завършва 5 от общо планираните 11 обекта в Гърция.'))
db.session.add(models.stock_divident(stock_id = 'GRM', divident_period = 3, amount = 0.2, company_information = 'Новоизградените им обекти водят до разширяване на пазарния им дял и по-добра печалба. Останалите обекти продължават да реализират значително по-слаби обороти.'))
db.session.add(models.stock_divident(stock_id = 'MSP', divident_period = 3, amount = 0.1, company_information = 'Започва бавно подобряване на пазарния дял.'))
db.session.add(models.stock_divident(stock_id = 'TBB', divident_period = 3, amount = 0.5, company_information = 'На компанията е наложена глоба за нелоялна конкуренция. Имиджът на веригата търпи големи загуби.'))
db.session.add(models.stock_divident(stock_id = 'SCT', divident_period = 3, amount = 0.9, company_information = 'Държи се стабилно на пазара и продължава да капитализира успешно.'))
db.session.add(models.stock_divident(stock_id = 'CLR', divident_period = 3, amount = 0.4, company_information = 'Отчита лек ръст'))
db.session.add(models.stock_divident(stock_id = 'STD', divident_period = 3, amount = 0.1, company_information = 'Отчита повишаване на количеството сключени застрахователни договори, но не и ръст в печалбата.'))
db.session.add(models.stock_divident(stock_id = 'INB', divident_period = 3, amount = 0, company_information = 'Преодолява финансовите си затруднения благодарение на намаляване на оперативните си разходи.'))
db.session.add(models.stock_divident(stock_id = 'BIP', divident_period = 3, amount = 0.08, company_information = 'Отичита ръст в продажбите си.'))
db.session.add(models.stock_divident(stock_id = 'FMP', divident_period = 3, amount = 0, company_information = 'Отичита ръст благодарение на подобрения си производствен капацитет.'))
db.session.add(models.stock_divident(stock_id = 'BFM', divident_period = 3, amount = 0.99, company_information = 'Отчита големи разходи за производство в следствие на лоша логистична политика.'))
db.session.add(models.stock_divident(stock_id = 'FFM', divident_period = 3, amount = 0, company_information = 'Продължава опитите си да се наложи на пазара чрез нова допълнителна инвестиция.'))
db.session.add(models.stock_divident(stock_id = 'NAS', divident_period = 4, amount = 0, company_information = 'Поради лошо финансово планиране, изпитват нужда от допълнителни инвестиции, за да завършат приложението.'))
db.session.add(models.stock_divident(stock_id = 'PPL', divident_period = 4, amount = 0.3, company_information = 'Поради разрастването им, усещат силен натиск от конкуренцията в бранша. '))
db.session.add(models.stock_divident(stock_id = 'CCS', divident_period = 4, amount = 0.3, company_information = 'Капитализират добре от дейността си в България, но прекратяват договора с немската компания. '))
db.session.add(models.stock_divident(stock_id = 'HRA', divident_period = 4, amount = 0, company_information = 'Новата версия на софтуера им се оказва огромен успех.'))
db.session.add(models.stock_divident(stock_id = 'PLG', divident_period = 4, amount = 0, company_information = 'Търсят нови инвеститори, за да завършат 13-тия хотел, който строят.'))
db.session.add(models.stock_divident(stock_id = 'RUT', divident_period = 4, amount = 0, company_information = 'Затваря 10% от офисите си в Русия.'))
db.session.add(models.stock_divident(stock_id = 'VLG', divident_period = 4, amount = 0.3, company_information = 'Конкуренцията в бранша се засилва, но успяват да запазят първото си място благодарение на вече изградени обекти.'))
db.session.add(models.stock_divident(stock_id = 'CLS', divident_period = 4, amount = 0, company_information = 'Започват нова рекламна кампания. Разходите по нея са високи.'))
db.session.add(models.stock_divident(stock_id = 'BIN', divident_period = 4, amount = 0.35, company_information = 'Експанзията на чуждия пазар започва да дава резултати. '))
db.session.add(models.stock_divident(stock_id = 'GRM', divident_period = 4, amount = 0.23, company_information = 'Взимат решение да затворят 30 % от големите си обекти и да изградят нови 20 обекта в места с голям човекопоток. Преорганизацията води до финансови затруднения.'))
db.session.add(models.stock_divident(stock_id = 'MSP', divident_period = 4, amount = 0.15, company_information = 'Продажбите отчитат лек ръст.'))
db.session.add(models.stock_divident(stock_id = 'TBB', divident_period = 4, amount = 0, company_information = 'Започват да предлагат стоки със собствената си марка на ниски цени.'))
db.session.add(models.stock_divident(stock_id = 'SCT', divident_period = 4, amount = 1.1, company_information = 'Взима се решение за увеличаване на капитала чрез публично предлагане на акции на нови инвеститори.'))
db.session.add(models.stock_divident(stock_id = 'CLR', divident_period = 4, amount = 0.42, company_information = 'Осъществява образователна кампания за важността на личното застраховане, след която отчита високи нива на ръст'))
db.session.add(models.stock_divident(stock_id = 'STD', divident_period = 4, amount = 0.05, company_information = 'Агресивното развитие продължава, компанията се старае да се развива на нови пазари и с нови продукти.'))
db.session.add(models.stock_divident(stock_id = 'INB', divident_period = 4, amount = 0.05, company_information = 'Разработва атрактивна ценова политика на задължителни застрахователни продукти.'))
db.session.add(models.stock_divident(stock_id = 'BIP', divident_period = 4, amount = 0.1, company_information = 'Не успява да посрещне новите капацитети на оборота си.'))
db.session.add(models.stock_divident(stock_id = 'FMP', divident_period = 4, amount = 0.15, company_information = 'Оптимализира разходите си за дистрибуция.'))
db.session.add(models.stock_divident(stock_id = 'BFM', divident_period = 4, amount = 0.95, company_information = 'Затваря един от заводите си, но успява да преразпредели производството между останалите'))
db.session.add(models.stock_divident(stock_id = 'FFM', divident_period = 4, amount = 0, company_information = 'Финансите на компанията са дестабилизирани. Френският производител налага нова ценова политика.'))
db.session.add(models.stock_divident(stock_id = 'NAS', divident_period = 5, amount = 0, company_information = 'Технически проблеми водят до забавяне на пускането на пазара на новото им приложение.  '))
db.session.add(models.stock_divident(stock_id = 'PPL', divident_period = 5, amount = 0.3, company_information = 'Страдат от засилена конкуренция'))
db.session.add(models.stock_divident(stock_id = 'CCS', divident_period = 5, amount = 0.4, company_information = 'Успяват да въведат нови технологии,благодарение на опита си с немския пазар и се радват на добра капитализация. '))
db.session.add(models.stock_divident(stock_id = 'HRA', divident_period = 5, amount = 0.5, company_information = 'Успяват да сключат договор с най-големите представители на Хорека сектора с продължителност на изпълнението 10 години.'))
db.session.add(models.stock_divident(stock_id = 'PLG', divident_period = 5, amount = 0, company_information = 'След провалени преговори с немски туроператор и руски туроператор, отчитат спад от 23% спрямо предходната година.'))
db.session.add(models.stock_divident(stock_id = 'RUT', divident_period = 5, amount = 0, company_information = 'Стартира нов тип ценова политика, за да насърчи по-нисък клас туристи.'))
db.session.add(models.stock_divident(stock_id = 'VLG', divident_period = 5, amount = 0.35, company_information = 'Започват строителство на висок клас комплекси.'))
db.session.add(models.stock_divident(stock_id = 'CLS', divident_period = 5, amount = 0, company_information = 'Успяват да балансират финансите си. '))
db.session.add(models.stock_divident(stock_id = 'BIN', divident_period = 5, amount = 0.45, company_information = 'Довършва изграждането на 11те обекта в Гърция. '))
db.session.add(models.stock_divident(stock_id = 'GRM', divident_period = 5, amount = 0.1, company_information = 'С новата си стратегия отчитат 15% ръст в продажбите.'))
db.session.add(models.stock_divident(stock_id = 'MSP', divident_period = 5, amount = 0.19, company_information = 'Затварят част от обектите си като се концентрират в градовете,където отчитат най-добри резултати.'))
db.session.add(models.stock_divident(stock_id = 'TBB', divident_period = 5, amount = 0.3, company_information = 'Възвръщат позиции като предпочитана верига за нисък клас продукти. '))
db.session.add(models.stock_divident(stock_id = 'SCT', divident_period = 5, amount = 1.2, company_information = 'Слива се с петото по големина застрахователно дружество в България.'))
db.session.add(models.stock_divident(stock_id = 'CLR', divident_period = 5, amount = 0.46, company_information = 'Задълбочава продуктите си в областта на застраховка "Живот", което се отразява благоприятно на печалбата'))
db.session.add(models.stock_divident(stock_id = 'STD', divident_period = 5, amount = 0.1, company_information = 'Поради липса на ръст в печалбата, двама от основните инвеститори се оттеглят.'))
db.session.add(models.stock_divident(stock_id = 'INB', divident_period = 5, amount = 0.1, company_information = 'Отчита ръст. '))
db.session.add(models.stock_divident(stock_id = 'BIP', divident_period = 5, amount = 0.1, company_information = 'Престукторира управлението в края на годината поради предхождаща дестабилизация. '))
db.session.add(models.stock_divident(stock_id = 'FMP', divident_period = 5, amount = 0.2, company_information = 'Успява да сключи договор за внос в България с испански производител на лекарствени продукти от по-висок клас.'))
db.session.add(models.stock_divident(stock_id = 'BFM', divident_period = 5, amount = 0.95, company_information = 'Изместен е от първото място в сектора, поради внос на чужди международни продукти на по-ниски цени.'))
db.session.add(models.stock_divident(stock_id = 'FFM', divident_period = 5, amount = 0, company_information = 'Компанията е обявена в несъстоятелноств края на календарната година.'))
db.session.add(models.stock_divident(stock_id = 'NAS', divident_period = 6, amount = 0, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'PPL', divident_period = 6, amount = 0.2, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'CCS', divident_period = 6, amount = 0.5, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'HRA', divident_period = 6, amount = 0.99, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'PLG', divident_period = 6, amount = 0, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'RUT', divident_period = 6, amount = 0.1, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'VLG', divident_period = 6, amount = 0.38, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'CLS', divident_period = 6, amount = 0.45, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'BIN', divident_period = 6, amount = 0.6, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'GRM', divident_period = 6, amount = 0.15, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'MSP', divident_period = 6, amount = 0.3, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'TBB', divident_period = 6, amount = 0.7, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'SCT', divident_period = 6, amount = 1.1, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'CLR', divident_period = 6, amount = 0.5, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'STD', divident_period = 6, amount = 0, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'INB', divident_period = 6, amount = 0.3, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'BIP', divident_period = 6, amount = 0.12, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'FMP', divident_period = 6, amount = 0.26, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'BFM', divident_period = 6, amount = 0.85, company_information = ''))
db.session.add(models.stock_divident(stock_id = 'FFM', divident_period = 6, amount = 0, company_information = ''))

db.session.add(models.gold_oil(gold_oil = 'gold'))
db.session.add(models.gold_oil(gold_oil = 'oil'))

db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 1, price = 115.71))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 2, price = 116.32))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 3, price = 117.54))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 4, price = 119.41))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 5, price = 119.21))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 6, price = 124.43))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 7, price = 127.32))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 8, price = 132.45))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 9, price = 147.64))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 10, price = 153))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 11, price = 159.53))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 12, price = 160.83))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 13, price = 154.61))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 14, price = 147.44))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 15, price = 140.68))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 16, price = 136.72))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 17, price = 120.21))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 18, price = 120.01))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 19, price = 119.43))
db.session.add(models.gold_oil_prices(gold_oil = 'oil', time = 20, price = 118.01))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 1, price = 210.43))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 2, price = 208.45))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 3, price = 206.83))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 4, price = 204.21))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 5, price = 203.55))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 6, price = 201.12))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 7, price = 200.42))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 8, price = 198.42))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 9, price = 197.35))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 10, price = 196.32))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 11, price = 195.22))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 12, price = 193.33))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 13, price = 196.42))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 14, price = 200.65))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 15, price = 209.59))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 16, price = 215.33))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 17, price = 214.22))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 18, price = 212.59))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 19, price = 211.01))
db.session.add(models.gold_oil_prices(gold_oil = 'gold', time = 20, price = 209.21))

db.session.add(models.bond_details(currency_code = 'EUR', country_name = 'Германия - ЕС', nominal_value = 1000))
db.session.add(models.bond_details(currency_code = 'USD', country_name = 'САЩ', nominal_value = 1000))
db.session.add(models.bond_details(currency_code = 'RSS', country_name = 'Русия', nominal_value = 500))
db.session.add(models.bond_details(currency_code = 'CNY', country_name = 'Китай', nominal_value = 5000))
db.session.add(models.bond_details(currency_code = 'BRL', country_name = 'Бразилия', nominal_value = 2000))

db.session.add(models.currency_price(currency_code = 'USD', time = 1, lv_price = 1.8))
db.session.add(models.currency_price(currency_code = 'USD', time = 2, lv_price = 1.82))
db.session.add(models.currency_price(currency_code = 'USD', time = 3, lv_price = 1.83))
db.session.add(models.currency_price(currency_code = 'USD', time = 4, lv_price = 1.85))
db.session.add(models.currency_price(currency_code = 'USD', time = 5, lv_price = 1.84))
db.session.add(models.currency_price(currency_code = 'USD', time = 6, lv_price = 1.86))
db.session.add(models.currency_price(currency_code = 'USD', time = 7, lv_price = 1.85))
db.session.add(models.currency_price(currency_code = 'USD', time = 8, lv_price = 1.86))
db.session.add(models.currency_price(currency_code = 'USD', time = 9, lv_price = 1.85))
db.session.add(models.currency_price(currency_code = 'USD', time = 10, lv_price = 1.86))
db.session.add(models.currency_price(currency_code = 'USD', time = 11, lv_price = 1.88))
db.session.add(models.currency_price(currency_code = 'USD', time = 12, lv_price = 1.85))
db.session.add(models.currency_price(currency_code = 'USD', time = 13, lv_price = 1.87))
db.session.add(models.currency_price(currency_code = 'USD', time = 14, lv_price = 1.89))
db.session.add(models.currency_price(currency_code = 'USD', time = 15, lv_price = 1.9))
db.session.add(models.currency_price(currency_code = 'USD', time = 16, lv_price = 1.91))
db.session.add(models.currency_price(currency_code = 'USD', time = 17, lv_price = 1.9))
db.session.add(models.currency_price(currency_code = 'USD', time = 18, lv_price = 1.92))
db.session.add(models.currency_price(currency_code = 'USD', time = 19, lv_price = 1.92))
db.session.add(models.currency_price(currency_code = 'USD', time = 20, lv_price = 1.92))
db.session.add(models.currency_price(currency_code = 'EUR', time = 1, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 2, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 3, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 4, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 5, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 6, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 7, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 8, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 9, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 10, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 11, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 12, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 13, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 14, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 15, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 16, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 17, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 18, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 19, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'EUR', time = 20, lv_price = 1.95))
db.session.add(models.currency_price(currency_code = 'CNY', time = 1, lv_price = 0.29))
db.session.add(models.currency_price(currency_code = 'CNY', time = 2, lv_price = 0.3))
db.session.add(models.currency_price(currency_code = 'CNY', time = 3, lv_price = 0.32))
db.session.add(models.currency_price(currency_code = 'CNY', time = 4, lv_price = 0.33))
db.session.add(models.currency_price(currency_code = 'CNY', time = 5, lv_price = 0.32))
db.session.add(models.currency_price(currency_code = 'CNY', time = 6, lv_price = 0.33))
db.session.add(models.currency_price(currency_code = 'CNY', time = 7, lv_price = 0.33))
db.session.add(models.currency_price(currency_code = 'CNY', time = 8, lv_price = 0.34))
db.session.add(models.currency_price(currency_code = 'CNY', time = 9, lv_price = 0.35))
db.session.add(models.currency_price(currency_code = 'CNY', time = 10, lv_price = 0.35))
db.session.add(models.currency_price(currency_code = 'CNY', time = 11, lv_price = 0.36))
db.session.add(models.currency_price(currency_code = 'CNY', time = 12, lv_price = 0.37))
db.session.add(models.currency_price(currency_code = 'CNY', time = 13, lv_price = 0.35))
db.session.add(models.currency_price(currency_code = 'CNY', time = 14, lv_price = 0.36))
db.session.add(models.currency_price(currency_code = 'CNY', time = 15, lv_price = 0.36))
db.session.add(models.currency_price(currency_code = 'CNY', time = 16, lv_price = 0.35))
db.session.add(models.currency_price(currency_code = 'CNY', time = 17, lv_price = 0.34))
db.session.add(models.currency_price(currency_code = 'CNY', time = 18, lv_price = 0.33))
db.session.add(models.currency_price(currency_code = 'CNY', time = 19, lv_price = 0.32))
db.session.add(models.currency_price(currency_code = 'CNY', time = 20, lv_price = 0.31))
db.session.add(models.currency_price(currency_code = 'RSS', time = 1, lv_price = 3.58))
db.session.add(models.currency_price(currency_code = 'RSS', time = 2, lv_price = 3.54))
db.session.add(models.currency_price(currency_code = 'RSS', time = 3, lv_price = 3.46))
db.session.add(models.currency_price(currency_code = 'RSS', time = 4, lv_price = 3.41))
db.session.add(models.currency_price(currency_code = 'RSS', time = 5, lv_price = 3.35))
db.session.add(models.currency_price(currency_code = 'RSS', time = 6, lv_price = 3.32))
db.session.add(models.currency_price(currency_code = 'RSS', time = 7, lv_price = 3.29))
db.session.add(models.currency_price(currency_code = 'RSS', time = 8, lv_price = 3.28))
db.session.add(models.currency_price(currency_code = 'RSS', time = 9, lv_price = 3.23))
db.session.add(models.currency_price(currency_code = 'RSS', time = 10, lv_price = 3.18))
db.session.add(models.currency_price(currency_code = 'RSS', time = 11, lv_price = 3.15))
db.session.add(models.currency_price(currency_code = 'RSS', time = 12, lv_price = 3.06))
db.session.add(models.currency_price(currency_code = 'RSS', time = 13, lv_price = 3))
db.session.add(models.currency_price(currency_code = 'RSS', time = 14, lv_price = 3.01))
db.session.add(models.currency_price(currency_code = 'RSS', time = 15, lv_price = 3.02))
db.session.add(models.currency_price(currency_code = 'RSS', time = 16, lv_price = 3.03))
db.session.add(models.currency_price(currency_code = 'RSS', time = 17, lv_price = 2.94))
db.session.add(models.currency_price(currency_code = 'RSS', time = 18, lv_price = 2.93))
db.session.add(models.currency_price(currency_code = 'RSS', time = 19, lv_price = 2.89))
db.session.add(models.currency_price(currency_code = 'RSS', time = 20, lv_price = 2.81))
db.session.add(models.currency_price(currency_code = 'BRL', time = 1, lv_price = 0.59))
db.session.add(models.currency_price(currency_code = 'BRL', time = 2, lv_price = 0.56))
db.session.add(models.currency_price(currency_code = 'BRL', time = 3, lv_price = 0.53))
db.session.add(models.currency_price(currency_code = 'BRL', time = 4, lv_price = 0.52))
db.session.add(models.currency_price(currency_code = 'BRL', time = 5, lv_price = 0.53))
db.session.add(models.currency_price(currency_code = 'BRL', time = 6, lv_price = 0.55))
db.session.add(models.currency_price(currency_code = 'BRL', time = 7, lv_price = 0.54))
db.session.add(models.currency_price(currency_code = 'BRL', time = 8, lv_price = 0.52))
db.session.add(models.currency_price(currency_code = 'BRL', time = 9, lv_price = 0.53))
db.session.add(models.currency_price(currency_code = 'BRL', time = 10, lv_price = 0.56))
db.session.add(models.currency_price(currency_code = 'BRL', time = 11, lv_price = 0.57))
db.session.add(models.currency_price(currency_code = 'BRL', time = 12, lv_price = 0.59))
db.session.add(models.currency_price(currency_code = 'BRL', time = 13, lv_price = 0.61))
db.session.add(models.currency_price(currency_code = 'BRL', time = 14, lv_price = 0.6))
db.session.add(models.currency_price(currency_code = 'BRL', time = 15, lv_price = 0.63))
db.session.add(models.currency_price(currency_code = 'BRL', time = 16, lv_price = 0.65))
db.session.add(models.currency_price(currency_code = 'BRL', time = 17, lv_price = 0.64))
db.session.add(models.currency_price(currency_code = 'BRL', time = 18, lv_price = 0.66))
db.session.add(models.currency_price(currency_code = 'BRL', time = 19, lv_price = 0.63))
db.session.add(models.currency_price(currency_code = 'BRL', time = 20, lv_price = 0.64))

db.session.add(models.bond_interest(country_code = 'USD', time = 1, interest_rate = 0.003))
db.session.add(models.bond_interest(country_code = 'USD', time = 2, interest_rate = 0.004))
db.session.add(models.bond_interest(country_code = 'USD', time = 3, interest_rate = 0.004))
db.session.add(models.bond_interest(country_code = 'USD', time = 4, interest_rate = 0.005))
db.session.add(models.bond_interest(country_code = 'USD', time = 5, interest_rate = 0.007))
db.session.add(models.bond_interest(country_code = 'USD', time = 6, interest_rate = 0.008))
db.session.add(models.bond_interest(country_code = 'USD', time = 7, interest_rate = 0.008))
db.session.add(models.bond_interest(country_code = 'USD', time = 8, interest_rate = 0.01))
db.session.add(models.bond_interest(country_code = 'USD', time = 9, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'USD', time = 10, interest_rate = 0.012))
db.session.add(models.bond_interest(country_code = 'USD', time = 11, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'USD', time = 12, interest_rate = 0.013))
db.session.add(models.bond_interest(country_code = 'USD', time = 13, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'USD', time = 14, interest_rate = 0.01))
db.session.add(models.bond_interest(country_code = 'USD', time = 15, interest_rate = 0.009))
db.session.add(models.bond_interest(country_code = 'USD', time = 16, interest_rate = 0.009))
db.session.add(models.bond_interest(country_code = 'USD', time = 17, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'USD', time = 18, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'USD', time = 19, interest_rate = 0.013))
db.session.add(models.bond_interest(country_code = 'USD', time = 20, interest_rate = 0.015))
db.session.add(models.bond_interest(country_code = 'EUR', time = 1, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 2, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 3, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 4, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 5, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 6, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 7, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 8, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 9, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 10, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 11, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 12, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 13, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 14, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 15, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 16, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 17, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 18, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 19, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'EUR', time = 20, interest_rate = 0.011))
db.session.add(models.bond_interest(country_code = 'CNY', time = 1, interest_rate = 0.022))
db.session.add(models.bond_interest(country_code = 'CNY', time = 2, interest_rate = 0.021))
db.session.add(models.bond_interest(country_code = 'CNY', time = 3, interest_rate = 0.02))
db.session.add(models.bond_interest(country_code = 'CNY', time = 4, interest_rate = 0.019))
db.session.add(models.bond_interest(country_code = 'CNY', time = 5, interest_rate = 0.021))
db.session.add(models.bond_interest(country_code = 'CNY', time = 6, interest_rate = 0.021))
db.session.add(models.bond_interest(country_code = 'CNY', time = 7, interest_rate = 0.02))
db.session.add(models.bond_interest(country_code = 'CNY', time = 8, interest_rate = 0.019))
db.session.add(models.bond_interest(country_code = 'CNY', time = 9, interest_rate = 0.019))
db.session.add(models.bond_interest(country_code = 'CNY', time = 10, interest_rate = 0.018))
db.session.add(models.bond_interest(country_code = 'CNY', time = 11, interest_rate = 0.017))
db.session.add(models.bond_interest(country_code = 'CNY', time = 12, interest_rate = 0.018))
db.session.add(models.bond_interest(country_code = 'CNY', time = 13, interest_rate = 0.019))
db.session.add(models.bond_interest(country_code = 'CNY', time = 14, interest_rate = 0.018))
db.session.add(models.bond_interest(country_code = 'CNY', time = 15, interest_rate = 0.02))
db.session.add(models.bond_interest(country_code = 'CNY', time = 16, interest_rate = 0.019))
db.session.add(models.bond_interest(country_code = 'CNY', time = 17, interest_rate = 0.02))
db.session.add(models.bond_interest(country_code = 'CNY', time = 18, interest_rate = 0.021))
db.session.add(models.bond_interest(country_code = 'CNY', time = 19, interest_rate = 0.02))
db.session.add(models.bond_interest(country_code = 'CNY', time = 20, interest_rate = 0.021))
db.session.add(models.bond_interest(country_code = 'RSS', time = 1, interest_rate = 0.06))
db.session.add(models.bond_interest(country_code = 'RSS', time = 2, interest_rate = 0.063))
db.session.add(models.bond_interest(country_code = 'RSS', time = 3, interest_rate = 0.066))
db.session.add(models.bond_interest(country_code = 'RSS', time = 4, interest_rate = 0.067))
db.session.add(models.bond_interest(country_code = 'RSS', time = 5, interest_rate = 0.069))
db.session.add(models.bond_interest(country_code = 'RSS', time = 6, interest_rate = 0.07))
db.session.add(models.bond_interest(country_code = 'RSS', time = 7, interest_rate = 0.071))
db.session.add(models.bond_interest(country_code = 'RSS', time = 8, interest_rate = 0.073))
db.session.add(models.bond_interest(country_code = 'RSS', time = 9, interest_rate = 0.076))
db.session.add(models.bond_interest(country_code = 'RSS', time = 10, interest_rate = 0.077))
db.session.add(models.bond_interest(country_code = 'RSS', time = 11, interest_rate = 0.079))
db.session.add(models.bond_interest(country_code = 'RSS', time = 12, interest_rate = 0.081))
db.session.add(models.bond_interest(country_code = 'RSS', time = 13, interest_rate = 0.083))
db.session.add(models.bond_interest(country_code = 'RSS', time = 14, interest_rate = 0.084))
db.session.add(models.bond_interest(country_code = 'RSS', time = 15, interest_rate = 0.085))
db.session.add(models.bond_interest(country_code = 'RSS', time = 16, interest_rate = 0.086))
db.session.add(models.bond_interest(country_code = 'RSS', time = 17, interest_rate = 0.089))
db.session.add(models.bond_interest(country_code = 'RSS', time = 18, interest_rate = 0.092))
db.session.add(models.bond_interest(country_code = 'RSS', time = 19, interest_rate = 0.093))
db.session.add(models.bond_interest(country_code = 'RSS', time = 20, interest_rate = 0.095))
db.session.add(models.bond_interest(country_code = 'BRL', time = 1, interest_rate = 0.046))
db.session.add(models.bond_interest(country_code = 'BRL', time = 2, interest_rate = 0.047))
db.session.add(models.bond_interest(country_code = 'BRL', time = 3, interest_rate = 0.049))
db.session.add(models.bond_interest(country_code = 'BRL', time = 4, interest_rate = 0.05))
db.session.add(models.bond_interest(country_code = 'BRL', time = 5, interest_rate = 0.051))
db.session.add(models.bond_interest(country_code = 'BRL', time = 6, interest_rate = 0.053))
db.session.add(models.bond_interest(country_code = 'BRL', time = 7, interest_rate = 0.053))
db.session.add(models.bond_interest(country_code = 'BRL', time = 8, interest_rate = 0.051))
db.session.add(models.bond_interest(country_code = 'BRL', time = 9, interest_rate = 0.049))
db.session.add(models.bond_interest(country_code = 'BRL', time = 10, interest_rate = 0.047))
db.session.add(models.bond_interest(country_code = 'BRL', time = 11, interest_rate = 0.046))
db.session.add(models.bond_interest(country_code = 'BRL', time = 12, interest_rate = 0.045))
db.session.add(models.bond_interest(country_code = 'BRL', time = 13, interest_rate = 0.044))
db.session.add(models.bond_interest(country_code = 'BRL', time = 14, interest_rate = 0.043))
db.session.add(models.bond_interest(country_code = 'BRL', time = 15, interest_rate = 0.043))
db.session.add(models.bond_interest(country_code = 'BRL', time = 16, interest_rate = 0.041))
db.session.add(models.bond_interest(country_code = 'BRL', time = 17, interest_rate = 0.042))
db.session.add(models.bond_interest(country_code = 'BRL', time = 18, interest_rate = 0.043))
db.session.add(models.bond_interest(country_code = 'BRL', time = 19, interest_rate = 0.044))
db.session.add(models.bond_interest(country_code = 'BRL', time = 20, interest_rate = 0.046))

db.session.add(models.gold_oil_info(gold_oil = 'oil', year_id = 1, gold_oil_information = 'Използват се находищата в Близкия изток. Страните от ОПЕК държат стабилни цени'))
db.session.add(models.gold_oil_info(gold_oil = 'oil', year_id = 2, gold_oil_information = 'Намаляват запасите в Близкия изток. '))
db.session.add(models.gold_oil_info(gold_oil = 'oil', year_id = 3, gold_oil_information = 'Находищата в Саудитска Арабия се изчерпват.'))
db.session.add(models.gold_oil_info(gold_oil = 'oil', year_id = 4, gold_oil_information = 'Русия започва експлоатация на нефтените си находища.'))
db.session.add(models.gold_oil_info(gold_oil = 'oil', year_id = 5, gold_oil_information = 'Поради европейските програми за възобновяеми енергийни източници, петролът пада.'))
db.session.add(models.gold_oil_info(gold_oil = 'gold', year_id = 1, gold_oil_information = 'Световната финансова криза свършва. Усилва се доверието в долара.'))
db.session.add(models.gold_oil_info(gold_oil = 'gold', year_id = 2, gold_oil_information = 'Реалните лихви в САЩ се увеличават.'))
db.session.add(models.gold_oil_info(gold_oil = 'gold', year_id = 3, gold_oil_information = 'Стабилна икономика на Европейския и Щатския пазар. Високи реални лихвени нива.'))
db.session.add(models.gold_oil_info(gold_oil = 'gold', year_id = 4, gold_oil_information = 'Търсенето от Китай рязко се покачва.'))
db.session.add(models.gold_oil_info(gold_oil = 'gold', year_id = 5, gold_oil_information = 'Щатската икономика се подобрява. Продължава високото търсене от страна на Китай'))

db.session.add(models.country_info(country_code = 'USD', year_id = 1, country_information = 'Започва бавно излизане от световната финансова криза. Регистрира се увеличен износ към Китай. Започват да се търсят кредити.'))
db.session.add(models.country_info(country_code = 'USD', year_id = 2, country_information = 'Увеличава се търсенето. Китай търсят  продукти от по-висок клас от САЩ. Икономиката на САЩ отчита ръст.'))
db.session.add(models.country_info(country_code = 'USD', year_id = 3, country_information = 'Търсене на недвижими имоти. Повишане банковото ипотечното банково кредитиране. Увеличава се търговията между САЩ и ЕС.'))
db.session.add(models.country_info(country_code = 'USD', year_id = 4, country_information = 'Намалява ръстът, липсва търговия с Китай, поради породилите се дипломатически затруднения в комуникацията.'))
db.session.add(models.country_info(country_code = 'USD', year_id = 5, country_information = 'Вътрешното търсене води до увеличени инвестиции и търговските отношения с ЕС се засилват. Отношенията с Китай продължават спада си.'))
db.session.add(models.country_info(country_code = 'EUR', year_id = 1, country_information = 'Пазарите продължават да са в рецесия поради свтовната финансова криза.'))
db.session.add(models.country_info(country_code = 'EUR', year_id = 2, country_information = 'Стабилизиране на вътрешния пазар.Увеличение при туризма от Китай. Започва спад на безработицата.'))
db.session.add(models.country_info(country_code = 'EUR', year_id = 3, country_information = 'Ръст на икономиката. Вътрешно търсене се подобрява.Спад на безработицата.'))
db.session.add(models.country_info(country_code = 'EUR', year_id = 4, country_information = 'Туристите от Китай секват.'))
db.session.add(models.country_info(country_code = 'EUR', year_id = 5, country_information = 'Има повече американски туристи.'))
db.session.add(models.country_info(country_code = 'CNY', year_id = 1, country_information = 'Инвестициите в производствения капацитет водят до повишаване на обемите на производство, което увеличава дохода на глава на население и вътрешното търсене. '))
db.session.add(models.country_info(country_code = 'CNY', year_id = 2, country_information = 'Икономиката се движи добре.'))
db.session.add(models.country_info(country_code = 'CNY', year_id = 3, country_information = 'Икономиката се запазва стабилитета си. Експортът към Русия се увеличава.'))
db.session.add(models.country_info(country_code = 'CNY', year_id = 4, country_information = 'Поради политически усложнения, Китай влошава отношенията си със САЩ и ЕС. Вносът и износът намаля. Повишават се инвестициите в злато.'))
db.session.add(models.country_info(country_code = 'CNY', year_id = 5, country_information = 'Дълбока рецесия и инфлация. Нямат пространство за износ. '))
db.session.add(models.country_info(country_code = 'RSS', year_id = 1, country_information = 'Свръхтърсене. Липса на импорт.'))
db.session.add(models.country_info(country_code = 'RSS', year_id = 2, country_information = 'Смяна на държавно управление. Смяна на правителството.'))
db.session.add(models.country_info(country_code = 'RSS', year_id = 3, country_information = 'Започва се политика на засилен внос от Китай на стоки от нисък клас.'))
db.session.add(models.country_info(country_code = 'RSS', year_id = 4, country_information = 'Държавната политика се насочва към усвояване на нефтения ресурс '))
db.session.add(models.country_info(country_code = 'RSS', year_id = 5, country_information = 'Поради европейските програми за възобновяеми енергийни източници.'))
db.session.add(models.country_info(country_code = 'BRL', year_id = 1, country_information = 'Протести заради дълбоко неравенство на населението.Спад на инвестициите.'))
db.session.add(models.country_info(country_code = 'BRL', year_id = 2, country_information = 'Смяна на държавно управление. Смяна на правителството.'))
db.session.add(models.country_info(country_code = 'BRL', year_id = 3, country_information = 'Държавна политика насочена към големи инфраструктурни проекти. Понижаване на нивата на безработица.'))
db.session.add(models.country_info(country_code = 'BRL', year_id = 4, country_information = 'Повишава се доходността от малкия и средния бизнес. Повишава се износът за САЩ.'))
db.session.add(models.country_info(country_code = 'BRL', year_id = 5, country_information = 'Държавните инфраструктурни проекти са довели до притеснения за твърде голям държавен дълг.'))

db.session.commit()